### ISSUE TITLE
CPR on Raspberry Pi

### ISSUE THREAD

**Issue by skipper85** [whoshuu/cpr#421] opened 2020-07-11 14:06 UTC
Hi there,

For a home project I would like to use CPR on the raspberry pi 2b+. I made a small test program to read and write data to a Rest Api, but the POST request hangs forever and is not executed on the Rest Api. The GET request works fine. I build the the same code also on my desktop(Ubuntu 20.04 amd64) and that gives no problems.
My first attempt was cross-compiling with various toolchains, but it always hangs on the POST/PUT request.
Finally I did a local build on the raspberry pi and it kept hanging on the POST request.

The c++ code is:
``` c++
#include <iostream>
#include <cpr/cpr.h>
#include "nlohmann/json.hpp"

using json = nlohmann::json;

int main()
{
	std::cout << "Hello World\n";

	auto r = cpr::Get(cpr::Url("http://192.168.10.188:3001/environment?select=location,pressure"));

		std::cout << r.status_code << std::endl;
		std::cout << r.header["content-type"] << std::endl;
		std::cout << r.text << std::endl;

	json msg;
	msg["location"] = "livingroom";
	msg["temperature"] = 27.5;
	msg["pressure"] = 1006.1;
	msg["humidity"] = 61;
	msg["time"] = "2020-07-01T13:21:22.18542+00:00";
	std::cout << msg.dump() << std::endl;
	r = cpr::Post(cpr::Url("http://192.168.10.188:3001/environment"),
				  cpr::Header{{"Content-Type", "application/json"},
							  {"Content-Length", std::to_string(msg.dump().length())}},
				  cpr::Body(msg.dump()));

	std::cout << r.status_code << std::endl;
	std::cout << r.header["content-type"] << std::endl;
	std::cout << r.text << std::endl;

	return 0;
}
```

my makefile is:
``` make
OBJECTS=build/main.o 

BUILDDIR=build/
SOURCEDIR=src/
LIB=-L/usr/local/lib/ -L/usr/local/lib
# include the src directory for rapidjson and spdlog includes
INC=-Isrc
MKDIR_P = mkdir -p

.PHONY : all
all: $(BUILDDIR)testCprSimple

$(BUILDDIR)testCprSimple : $(OBJECTS)
	g++ -o $(BUILDDIR)testCprSimple $(OBJECTS) $(LIB) -latomic -lcpr -lcurl

$(BUILDDIR)main.o : $(SOURCEDIR)main.cpp
	g++ -o $(BUILDDIR)main.o $(SOURCEDIR)main.cpp -std=c++14 $(INC) -g3 -O2 -Wall -c -fmessage-length=0

# There are two reasons to use a phony target: 
# to avoid a conflict with a file of the same name, and to improve performance. 	
.PHONY: clean
clean :
	rm $(BUILDDIR)testCprSimple $(OBJECTS)
# Tab must be used as indentation
```

I am using 2020-02-13-raspbian-buster-lite as OS on the raspberry pi with gcc (Raspbian 8.3.0-6+rpi1) 8.3.0

I have installed and build CPR successfully on the raspberry pi with:
``` bash
git clone https://github.com/whoshuu/cpr.git
cd cpr
git submodule update --init
mkdir build; cd build
cmake -DCMAKE_USE_OPENSSL=OFF ..
make
sudo make install
```

The curl program itself is working with POST request on the pi:
`curl http://192.168.10.188:3001/environment -X POST -H "Content-Type: application/json" -d '{"location":"livingroom", "temperature":23.2,"pressure":1002.5, "humidity":49, "time":"2020-07-01T13:21:22.18542+00:00"}'`

Am i forgetting something for the raspberry pi / arm build or is it a bug?
Thanks in advance for your help.

**Comment by dilshodm** [comment] 2020-07-11 16:15
How it works if you remove this:
```c++
{"Content-Length", std::to_string(msg.dump().length())}}
```
from cpr::Header?

**Comment by skipper85** [comment] 2020-07-11 16:58
Hi,
removing 
``` c++
{"Content-Length", std::to_string(msg.dump().length())}}
``` 
has no effect. On my desktop still works good and on my pi the POST request is not send and program keeps hanging.

**Comment by COM8** [comment] 2020-07-13 08:51
Why do you link against `-latomic -lcurl`, especially against `-lcurl`?
Looks to me like an outdated version of libcurl.

Could you please try to run all `CPR` unit tests with the following command:
```BASH
ctest -C release -V
# or
ctest -C debug -V
```

**Comment by skipper85** [comment] 2020-07-13 11:26
Hi,

The -lcurl was something to try out and -latomic was a remaining from the makefile from other project I copied from.
Current makfile is:
``` make
OBJECTS=build/main.o 

BUILDDIR=build/
SOURCEDIR=src/
LIB=-L/usr/local/lib/

.PHONY : all
all: $(BUILDDIR)testCprSimple

$(BUILDDIR)testCprSimple : $(OBJECTS)
	g++ -o $(BUILDDIR)testCprSimple $(OBJECTS) $(LIB) -lcpr

$(BUILDDIR)main.o : $(SOURCEDIR)main.cpp
	g++ -o $(BUILDDIR)main.o $(SOURCEDIR)main.cpp -std=c++14 $(INC) -g3 -O2 -Wall -c -fmessage-length=0

# There are two reasons to use a phony target: 
# to avoid a conflict with a file of the same name, and to improve performance. 	
.PHONY: clean
clean :
	rm $(BUILDDIR)testCprSimple $(OBJECTS)
# Tab must be used as indentation
```

Result from the test
``` bash
pi@raspberrypi:~/Downloads/cpr/build $ ctest -C release -V
UpdateCTestConfiguration  from :/home/pi/Downloads/cpr/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/pi/Downloads/cpr/build/DartConfiguration.tcl
Test project /home/pi/Downloads/cpr/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
      Start  1: cpr_get_tests

1: Test command: /home/pi/Downloads/cpr/build/bin/get_tests
1: Test timeout computed to be: 10000000
1: [==========] Running 95 tests from 11 test suites.
1: [----------] Global test environment set-up.
1: [----------] 6 tests from BasicTests
1: [ RUN      ] BasicTests.HelloWorldTest
1: [       OK ] BasicTests.HelloWorldTest (5 ms)
1: [ RUN      ] BasicTests.TimeoutTest
1: [       OK ] BasicTests.TimeoutTest (3 ms)
1: [ RUN      ] BasicTests.BasicJsonTest
1: [       OK ] BasicTests.BasicJsonTest (3 ms)
1: [ RUN      ] BasicTests.ResourceNotFoundTest
1: [       OK ] BasicTests.ResourceNotFoundTest (3 ms)
1: [ RUN      ] BasicTests.BadHostTest
1: [       OK ] BasicTests.BadHostTest (9 ms)
1: [ RUN      ] BasicTests.RequestBodyTest
 1/16 Test  #1: cpr_get_tests ....................***Exception: SegFault  1.06 sec
test 2
      Start  2: cpr_post_tests

2: Test command: /home/pi/Downloads/cpr/build/bin/post_tests
2: Test timeout computed to be: 10000000
2: [==========] Running 25 tests from 1 test suite.
2: [----------] Global test environment set-up.
2: [----------] 25 tests from UrlEncodedPostTests
2: [ RUN      ] UrlEncodedPostTests.UrlPostSingleTest
2: [       OK ] UrlEncodedPostTests.UrlPostSingleTest (6 ms)
2: [ RUN      ] UrlEncodedPostTests.UrlPostAddPayloadPair
2: [       OK ] UrlEncodedPostTests.UrlPostAddPayloadPair (4 ms)
2: [ RUN      ] UrlEncodedPostTests.UrlPostPayloadIteratorTest
2: [       OK ] UrlEncodedPostTests.UrlPostPayloadIteratorTest (4 ms)
2: [ RUN      ] UrlEncodedPostTests.UrlPostEncodeTest
2: [       OK ] UrlEncodedPostTests.UrlPostEncodeTest (4 ms)
2: [ RUN      ] UrlEncodedPostTests.UrlPostEncodeNoCopyTest
2: [       OK ] UrlEncodedPostTests.UrlPostEncodeNoCopyTest (3 ms)
2: [ RUN      ] UrlEncodedPostTests.UrlPostManyTest
2: [       OK ] UrlEncodedPostTests.UrlPostManyTest (4 ms)
2: [ RUN      ] UrlEncodedPostTests.UrlPostBadHostTest
2: [       OK ] UrlEncodedPostTests.UrlPostBadHostTest (12 ms)
2: [ RUN      ] UrlEncodedPostTests.FormPostSingleTest
2: [       OK ] UrlEncodedPostTests.FormPostSingleTest (5 ms)
2: [ RUN      ] UrlEncodedPostTests.FormPostFileTest
2: [       OK ] UrlEncodedPostTests.FormPostFileTest (6 ms)
2: [ RUN      ] UrlEncodedPostTests.FormPostFileNoCopyTest
2: [       OK ] UrlEncodedPostTests.FormPostFileNoCopyTest (6 ms)
2: [ RUN      ] UrlEncodedPostTests.FormPostFileBufferTest
2: [       OK ] UrlEncodedPostTests.FormPostFileBufferTest (4 ms)
2: [ RUN      ] UrlEncodedPostTests.FormPostFileBufferNoCopyTest
2: [       OK ] UrlEncodedPostTests.FormPostFileBufferNoCopyTest (5 ms)
2: [ RUN      ] UrlEncodedPostTests.FormPostFileBufferPointerTest
2: [       OK ] UrlEncodedPostTests.FormPostFileBufferPointerTest (4 ms)
2: [ RUN      ] UrlEncodedPostTests.FormPostFileBufferArrayTest
2: [       OK ] UrlEncodedPostTests.FormPostFileBufferArrayTest (5 ms)
2: [ RUN      ] UrlEncodedPostTests.FormPostFileBufferVectorTest
2: [       OK ] UrlEncodedPostTests.FormPostFileBufferVectorTest (4 ms)
2: [ RUN      ] UrlEncodedPostTests.FormPostFileBufferStdArrayTest
2: [       OK ] UrlEncodedPostTests.FormPostFileBufferStdArrayTest (4 ms)
2: [ RUN      ] UrlEncodedPostTests.FormPostManyTest
2: [       OK ] UrlEncodedPostTests.FormPostManyTest (4 ms)
2: [ RUN      ] UrlEncodedPostTests.FormPostManyNoCopyTest
2: [       OK ] UrlEncodedPostTests.FormPostManyNoCopyTest (4 ms)
2: [ RUN      ] UrlEncodedPostTests.FormPostContentTypeTest
2: [       OK ] UrlEncodedPostTests.FormPostContentTypeTest (3 ms)
2: [ RUN      ] UrlEncodedPostTests.FormPostContentTypeLValueTest
2: [       OK ] UrlEncodedPostTests.FormPostContentTypeLValueTest (3 ms)
2: [ RUN      ] UrlEncodedPostTests.UrlPostAsyncSingleTest
2: [       OK ] UrlEncodedPostTests.UrlPostAsyncSingleTest (14 ms)
2: [ RUN      ] UrlEncodedPostTests.UrlReflectTest
2: [       OK ] UrlEncodedPostTests.UrlReflectTest (4 ms)
2: [ RUN      ] UrlEncodedPostTests.PostWithNoBodyTest
2: [       OK ] UrlEncodedPostTests.PostWithNoBodyTest (3 ms)
2: [ RUN      ] UrlEncodedPostTests.PostReflectTest
```

The test hangs after PostReflectTest
Version of the curl is "curl/7.69.1-DEV", atleast that is in the succesful get request.
The post request still hangs with new build.

**Comment by COM8** [comment] 2020-07-15 11:05
I will have a look at it in the next couple of days.

**Comment by COM8** [comment] 2020-07-24 05:27
I can confirm this issue.
After upgrading my RPi CMaker version and  building CPR, `Post` tests fail.
Besides that, `Get` tests result in a segfault.

I think I have to set up GDB for debugging now.

**Comment by COM8** [comment] 2020-07-24 17:14
What I found out so far:
Tests seem to fail on an Raspberry Pi, since `mongoose` is throwing a segfault during initializing.
Or more concrete, when it tries to create a new `pthread`.

**Comment by COM8** [comment] 2020-07-24 17:19
Might be related to:

https://github.com/cesanta/mongoose/issues/845

**Comment by skipper85** [comment] 2020-07-28 21:05
Thanks for the update.
I tried out gdbserver on my Pi but did not get any further then this.

```
Program received signal SIGINT, Interrupt.
0x76cf987c in read () from target:/lib/arm-linux-gnueabihf/libc.so.6
```

**Comment by diedoman** [comment] 2020-09-08 12:22
Not sure if this information is very relevant, but we were using cpr 1.5.0 on raspbian buster as well, and ran into issues where the application would hang on HTTP POST calls (but only on raspbian/armhf, not on our 64 bit workstations). I have reverted our software to CPR 1.4.0 and that one seems to work just fine, so it seems to be present in version => 1.5.0

**Comment by COM8** [comment] 2021-01-20 13:35
I tested it on my Raspberry Pi 3 and everything works like expected. All tests pass with the latest `master` build.
Can anybody confirm this with their setup?

**Comment by jonathanhood** [comment] 2021-01-27 18:48
I was seeing a _very_ similiar issue using CPR 1.5.1 and Curl 7.73.0 on both a cortex-a7 and mipsel target. While this wasn't a raspberry pi, the symptoms where very much the same as described by the reporter. The segfault and/or hang (depending on how I constructed the arguments to `cpr::Post`) seemed to happen when cpr calls `curl_easy_perform` during the POST request process.

Upgrading to CPR 1.5.2 and Curl 7.74 seems to have resolved the issue. Perhaps the fixes to post content lengths in that release also resolved this issue?

**Comment by willem640** [comment] 2021-02-11 21:02
Might test this in a few days in my Pi 3B

**Comment by skipper85** [comment] 2021-02-14 20:36
Hi, I have tested the code on my raspberry pi 3B+ and it does not hang anymore. This time I ran the build in a docker container with libcpr.so.1.5.1 and curl 7.64.0. I created the image today, so I do not understand why the library is not 1.5.2 if that the latest version. I pulled it with git clone --depth 1 https://github.com/whoshuu/cpr.git, that should pull the latest version.

**Comment by COM8** [comment] 2021-02-26 14:02
Yes, this is actually a bug with the version :D

Besides that I'm closing this issue since it seams to be resolved for now.
Feel free to reopen in case this still persists.

**Closed by COM8** 2021-02-26 14:02 UTC
Labels: Awaiting Resonse :hourglass_flowing_sand:, Bug :bug:
