### ISSUE TITLE
Upload file name with multilingual

### ISSUE THREAD

**Issue by jojo0796** [whoshuu/cpr#595] opened 2021-07-20 10:52 UTC
I upload file with

cpr::Response r = cpr::Post(cpr::Url(cpr::Url{ szURL.c_str() }),
			     cpr::Multipart{ {"Filename", "切結書.jpeg"},
						   {"Filedata", cpr::File{"c:\\切結書.jpeg"}, "application/octet-stream"} }

and send data "filename="������.jpeg"" not transfer to utf-8

--------------------------f0fa9ab880cbecc9
Content-Disposition: form-data; name="Filename"

切結書.jpeg
--------------------------f0fa9ab880cbecc9
Content-Disposition: form-data; name="Filedata"; filename="������.jpeg"
Content-Type: application/octet-stream

**Comment by COM8** [comment] 2021-07-23 15:12
Dude it's really hard to read and understand your issues if you first of all do not highlight your code.
Again: https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf

Also please follow those guidelines for creating an issue: https://developers.google.com/blockly/guides/modify/contribute/write_a_good_issue

All in all I do not understand what you issue is.
Perhaps it might be a duplicate of this one: https://github.com/whoshuu/cpr/issues/590

**Closed by COM8** 2021-07-23 15:12 UTC
