### ISSUE TITLE
-D_GLIBCXX_DEBUG=1 introduces bugs

### ISSUE THREAD

**Issue by souaremsaidou** [whoshuu/cpr#358] opened 2020-03-29 12:53 UTC
What steps will reproduce the problem?
1. On Linux, compile Cpr with no specific flags to g++
2. Compile your program with **-D_GLIBCXX_DEBUG=1** and link against Cpr
3. It fails.
> undefined reference to `cpr::Session::SetOption(std::__debug::map<std::string, std::string, cpr::CaseInsensitiveCompare, std::allocator<std::pair<std::string const, std::string> > > const&)'
> [build] collect2: error: ld returned 1 exit status
4. Compile your program without g++ option **-D_GLIBCXX_DEBUG** and link against Cpr
5. it passes.

**Comment by jungletek** [comment] 2020-03-30 15:51
This is a linker error, the linker can't find libcpr.

This is not a bug, this is you not knowing how to use your tools.

**Comment by COM8** [comment] 2020-04-16 08:50
Ping @kingkili.

**Comment by KingKili** [comment] 2020-04-16 11:59
I quickly tried to reproduce it, and wasn't able to. Can you please give me your minimal example.

**Comment by souaremsaidou** [comment] 2020-04-16 12:49
@KingKili, it is easy to reporduce:
- compile Cpr without -D_GLIBCXX_DEBUG=1 
- then link againt it with -D_GLIBCXX_DEBUG=1 option or

**Comment by KingKili** [comment] 2020-04-16 14:14
It's not that simple. My [testproject](https://github.com/whoshuu/cpr/files/4487654/testproject.zip) compiles for example.

**Comment by COM8** [comment] 2020-06-19 06:56
Closing this since there has not been a response for a month now.

**Closed by COM8** 2020-06-19 06:56 UTC
Labels: Awaiting Resonse, Build
