### ISSUE TITLE
Unresolved external symbol

### ISSUE THREAD

**Issue by whyCPPgofast** [whoshuu/cpr#438] opened 2020-08-26 19:52 UTC
I know this issue was already closed #182  but the problem still persists.

Its my first time using this lib.
I cloned the repo, built it with CMake targeting Visual Studio 2019 (built as shared binaries, excluded tests).
I've included "include" directory, linked the "lib" directory and added the cpr.lib + curl-d_impl.lib as "input" links in my VS2019.

```c++
#include <iostream>
#include <string>
#include <cpr/cpr.h>

using namespace std;

int main() {
    cpr::Response r = cpr::Get(cpr::Url{ "https://httpbin.org/get" });
    r.status_code;
    r.header["content-type"];
    cout << r.text << endl;

    return 0;
}
```

![error](https://user-images.githubusercontent.com/70290351/91348899-c4e31e80-e7e4-11ea-8834-68c39080886e.jpg)

**Comment by COM8** [comment] 2020-08-27 06:21
I'm currently on vacation. I will have a look at it again, as soon as I'm back (~02.09).

**Comment by whyCPPgofast** [comment] 2020-08-27 16:54
@COM8 enjoy your vacation!

**Comment by COM8** [comment] 2020-09-03 14:09
I can confirm this behavior and I do not know why this happens.
I guess this is related to how CMake build the lib.

@KingKili didn't we encounter the same problem in an earlier version?

**Comment by COM8** [comment] 2021-03-19 16:30
Closing this since [cpr v1.6.0](https://github.com/whoshuu/cpr/releases/tag/1.6.0) has been released including a bunch of fixes for Windows and SSL in general.
Feel free to reopen in case this issue still exists.

**Closed by COM8** 2021-03-19 16:30 UTC
Labels: Build :construction_worker:, Needs Investigation :mag:, Windows :tv:
