### ISSUE TITLE
Timeout logic falter

### ISSUE THREAD

**Issue by Rockybilly** [whoshuu/cpr#468] opened 2020-11-02 13:57 UTC
Greetings,

I know that the timeout logic in this library is based on libcurl. However, there is a simple inconsistency when dealing with real world situations. I will give you examples. Lets say I set 120s (120000 ms) to a timeout.

**Example:**

``` 
cpr::Response r = cpr::Post(cpr::Url{"link"},
    cpr::Header{{"Authorization", "Bearer " + token},
    {"Content-Type","application/json"},
    {"Content-Length", std::to_string(string_buffer_json.GetLength())}},
    cpr::Body{string_buffer_json.GetString()},
    cpr::Timeout{120000});
```
**Situations:**

1. Server returns 200. (request succeeds)
2. Destination server does not respond or returns HTTP 404 etc. (No problem, request fails or timeouts).
3. Server returns 200, begins transferring the body, then some internet problem occurs, or download takes too long., request never completes. (Request should fail)

In the last case, the request does not fail, tries to serve the body as it received. This presents some problem (incomplete body). I can't check the integrity of each response body before processing, it would be very ineffective. But the if a request fails this way, it still gives HTTP 200 (which is true of course), but the body is faulty. As far as I can see it does not produce a `cpr::Response.error`. 

I want to use timeouts, I don't want my program to halt indefinitely.

How does the `cpr` library recommend we do in such a situation ? Here are some suggestions.

- Check `r.header["Content-Length"]` versus `r.text.length()` (If Content-Length is optional, this presents problem).
- Create a two layer timeout mechanism, one to check if request took unreasonable time, the other to cancel the request (cpr timeout). Like, cpr timeout is 120s, but if it took longer than 60s, just discard it, body may be incomplete.
- Discover a method to check if the request is terminated by timeout.

Thank you for your time.

**Comment by COM8** [comment] 2020-11-02 16:51
Currently this behaviour is undefined behaviour.
But I think I can fix this, so it returns with an error.

**Comment by Rockybilly** [comment] 2020-11-02 16:57
> 
> 
> Currently this behaviour is undefined behaviour.
> But I think I can fix this, so it returns with an error.

The most important fix would be resetting the `response.status` to 0 (I guess you use that for failed requests). Given that mostly people check `r.status_code == 200` for executing success situation code. Second thing would be adding an appropriate error of course.

**Comment by COM8** [comment] 2021-01-20 11:07
I was not able to reproduce this behaviour on my side.
To me it looks like the requested behaviour is already present in CPR.
Could you please come up with a concrete test case, that reproduces this behaviour?

Here: https://github.com/whoshuu/cpr/commit/9a8689e16b224cb9b9b4b5f3cfd4e815501552ea

**Comment by Rockybilly** [comment] 2021-03-15 22:11
> 
> 
> I was not able to reproduce this behaviour on my side.
> To me it looks like the requested behaviour is already present in CPR.
> Could you please come up with a concrete test case, that reproduces this behaviour?
> 
> Here: [9a8689e](https://github.com/whoshuu/cpr/commit/9a8689e16b224cb9b9b4b5f3cfd4e815501552ea)

I can't easily reproduce the problem myself too because, it would be hard to find a problematic server (the original ones that made me open the issue are gone). All I can say is, this problem is maybe present with chunked encoding, but I can't guarantee if it's a server side issue, or a cpr one.

**Comment by COM8** [comment] 2021-03-19 16:28
Closing this since there is no answer.
Feel free to reopen in case you can reproduce this.

**Closed by COM8** 2021-03-19 16:28 UTC
Labels: Awaiting Resonse :hourglass_flowing_sand:, Bug :bug:
