### ISSUE TITLE
Problem setting header to application/json

### ISSUE THREAD

**Issue by slzatz** [whoshuu/cpr#449] opened 2020-09-22 21:27 UTC
I am having problems using cpr to connect to Compiler Explorer's api.  When I put wireshark on my cpr post request, it says that the header content-type is `x-www-form-urlencoded` but my code has Header{{"Content-Type", "application/json"}}.  I don't have much experience with wireshark or cpr but is it possible that my header directive is not being followed.  I am wondering if this is the reason that I can't connect with Compiler Explorer.

**Comment by COM8** [comment] 2020-09-23 08:02
Interesting.
Could you please provide a small example program or test, showing this behaviour?

**Comment by bayec** [comment] 2020-09-23 09:46
I have a similar question. Here's the code I wrote. Run it, I found some problems by Wireshark. `Content-Length` is 240518168632, and `Expect` is 100-continue. Please help me, thanks.

```c++
std::string body = "{\"RegisterObject\": {\"DeviceID\": \"65010000005030000001\"}}";
auto response    = cpr::Post(cpr::Url{"http://10.10.10.235:14000/VIID/System/Register"},
                               cpr::Header{{"Content-Type", "application/json"}}, cpr::Body{body},
                               cpr::ConnectTimeout{3000}, cpr::Timeout{3000});
```
![cpr](https://user-images.githubusercontent.com/16732948/93995045-191cf680-fdc3-11ea-8e53-936cfe244b3e.png)

**Comment by slzatz** [comment] 2020-09-23 09:58
The following code sent to httpbin.org:

```
json js = {{"key", "value"}};
cpr::Response r = cpr::Post(cpr::Url{http://httpbin.org/post"),
                                            Body{js.dump()},
                                            cpr::Header{{"Content-Type", "application/json"}},
                                            cpr::Header{{"accept", "application/json"}}
                                            );
```
returns the following from httpbin:
```
{
  "args": {},
  "data": "",
  "files": {},
   "form": {
   {"{\"key\":\"value\"}" : ""
  }, 
   "headers": {                                                                                                                                                                                      
     "Accept": "application/json",                                                                                                                                                             
     "Accept-Encoding": "deflate, gzip",                                                                                                                                                       
     "Content-Length": "15", 
     "Content-Type": "application/x-www-form-urlencoded",                                                                                                                                      
     "Host": "httpbin.org",                                                                                                                                                                    
     "User-Agent": "curl/7.69.1",
     "X-Amzn-Trace-Id": "Root=1-5f6b1491-8761a87669d2a28a432c8a10"
 }, 
  "json": null,
  "origin": "148.75.169.112",
  "url": "http://httpbin.org/post"                                                                                                                                                                                   }                                         
```

**Comment by COM8** [comment] 2020-09-23 11:55
@slzatz, I'm unable to reproduce your problem.
I wrote a quick test and everything seams to run like expected:
```c++
TEST(UrlEncodedPostTests, HttpBinPostTest) {
    Url url{server->GetBaseUrl() + "/json_post.html"};
    std::string body{"{\"RegisterObject\": {\"DeviceID\": \"65010000005030000001\"}}"};
    cpr::Response response = cpr::Post(cpr::Url{"http://httpbin.org/post"}, cpr::Body{body},
                                       cpr::Header{{"Content-Type", "application/json"}},
                                       cpr::Header{{"accept", "application/json"}});
    EXPECT_EQ(std::string{"application/json"}, response.header["content-type"]);
    EXPECT_EQ(200, response.status_code);
    EXPECT_EQ(ErrorCode::OK, response.error.code);
}
```

Did I miss anything?

**Comment by LukeMauldin** [comment] 2020-09-23 12:04
I have experienced this same problem using cpr::Session Post. I am manually setting the Header Content Type but is being overridden and set to ‘x-www-form-urlencoded’

**Comment by slzatz** [comment] 2020-09-23 14:10
@COM8 Not sure how to reconcile the test you posted and what I am experiencing and what @LukeMauldin reports as well. Just to eliminate the unlikely event that somehow the json library doing something unexpected, I initialized the body with the same string as in your test and I still get the content type as `x-www-form-urlencoded`.  It is as cpr is ignoring my Header and the post is falling back to the default content type.

**Comment by xloem** [comment] 2020-09-23 16:40
Has anybody tried older versions of cpr to see if they are caused by this?
Does anybody have a binary or complete sourcefile that can reproduce the issue?
What operating system is this running on?  Are threads involved, or other uses of curl outside cpr?

**Comment by xloem** [comment] 2020-09-23 16:46
I posted a comment here before fully understanding the situation.  It sounds like the internals working with curl need debugging using a packetlogger.  One way somebody could pursue this without much knowledge is by making a working example using raw libcurl and incrementally changing the parts to those of cpr instead.

**Comment by slzatz** [comment] 2020-09-23 19:30
Well here's a clue, if I send only one Header, the Content-Type is set correctly.  As soon as I send the Accept Header, the Content-Type reverts to `x-www-form-urlencoded`.  (Doesn't solve my problem because I need the Accept Header.)  So the code below at least sets the Content Type correctly.

```
json js = {{"key", "value"}};
cpr::Response r = cpr::Post(cpr::Url{http://httpbin.org/post"),
                                            Body{js.dump()},
                                            cpr::Header{{"Content-Type", "application/json"}}
                                            //cpr::Header{{"accept", "application/json"}}
                                            );
```
I took a quick look at the code and not clear under what circumstances the append on line 136 fails (if that is what is going on) but also not sure it makes sense to keep evaluating further headers in the for loop once `curl_slist_append` returns a nullptr.

```
curl_slist* temp = curl_slist_append(chunk, header_string.c_str());
            if (temp) {
                chunk = temp;
            }
```

**Comment by xloem** [comment] 2020-09-23 21:03
Glancing at the code you mention, it looks like the call to setHeader does indeed reset the headers.  Your issue would be fixed by wrapping both headers into one Header object.  I wonder if that's documented.

**Comment by slzatz** [comment] 2020-09-23 21:41
@xloem - Thanks - you were correct that you can wrap both headers in one header object and that worked.  Thanks for your help.  Still seems worth figuring out why separate header calls appear to fail and under what circumstances.

**Comment by COM8** [comment] 2020-09-24 08:38
Yes, good spot @xloem.
Yes, by setting multiple `cpr::Header` objects, headers will be overriden/cleared each time.

This is a good point. We might have to ask ourselves how we could prevent such behaviour in the best case even during compilation.

**Closed by COM8** 2020-09-24 08:38 UTC
Labels: Needs Investigation :mag:, Question :question:
