### ISSUE TITLE
https doesn't work on Windows

### ISSUE THREAD

**Issue by thunderstorm010** [whoshuu/cpr#509] opened 2021-01-22 21:16 UTC
So, I have OpenSSL installed and c++ requests is built with OpenSSL support but i just get a newline on a get request.
My C++ code:
```cpp
#include <iostream>
#include <cpr/cpr.h>

int main() {
    cpr::Response resp = cpr::Get(cpr::Url{"https://httpbin.org/get"});

    std::cout << resp.text << std::endl;
    return 0;
}
```
My CMakeLists
```cmake
cmake_minimum_required(VERSION 3.17)
project(tandrmizaj)

set(CMAKE_CXX_STANDARD 11)

add_executable(tandrmizaj main.cpp)

set(BUILD_SHARED_LIBS ON)

include(FetchContent)
FetchContent_Declare(cpr GIT_REPOSITORY https://github.com/whoshuu/cpr.git GIT_TAG c8d33915dbd88ad6c92b258869b03aba06587ff9) # the commit hash for 1.5.0
FetchContent_MakeAvailable(cpr)

target_link_libraries(tandrmizaj PRIVATE cpr::cpr)
```

And this is the output:

```
C:\Users\teslafan\CLionProjects\tandrmizaj\cmake-build-debug\tandrmizaj.exe


Process finished with exit code 0
```

**Comment by COM8** [comment] 2021-01-24 08:29
This might help: https://github.com/whoshuu/cpr/issues/493

**Comment by thunderstorm010** [comment] 2021-01-24 10:37
No, I can build with/without OpenSSL. Even if I enable WinSSL (schannel), the same thing happens. Just at runtime, blank output.

**Comment by COM8** [comment] 2021-02-26 15:53
Ok. Had a look at it.
The problem is: "SSL certificate problem: unable to get local issuer certificate" when using it with OpenSSL and a completely broken request, when WINSSL is beeing used.

@KingKili I think we need to refactor the Windows build completely.
There are a lot of issues. I will create a new issue for this.

**Comment by COM8** [comment] 2021-02-26 15:55
#520

**Comment by KingKili** [comment] 2021-03-05 08:47
> Ok. Had a look at it.
> The problem is: "SSL certificate problem: unable to get local issuer certificate" when using it with OpenSSL and a completely broken request, when WINSSL is beeing used.
> 
> @KingKili I think we need to refactor the Windows build completely.
> There are a lot of issues. I will create a new issue for this.

I do not see much room to refactor the build for windows. We are pretty much using standard CMake. I think most problems are comming from libcurl, but there is not much we can do about them. 
The only thing were we can try to fix things is to get rid of [CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS](https://github.com/whoshuu/cpr/blob/master/CMakeLists.txt#L8) and annotate the code of cpr. But it is uncertain if it would fix any problems.

**Comment by COM8** [comment] 2021-03-05 08:50
This might be interesting https://github.com/whoshuu/cpr/issues/520

**Comment by KingKili** [comment] 2021-03-05 09:09
I will have a look. I currently adding CI for static builds. But we can also think about linking statically against libcurl. This should simplify things in the future.

**Comment by c0nd3v** [comment] 2021-03-12 21:21
I think everyone here should go take a look at my comment, it should provide more context into this issue
https://github.com/whoshuu/cpr/issues/520#issuecomment-797760364

**Comment by COM8** [comment] 2021-03-15 12:28
Can somebody test #529. This should fix a lot of issues related to Windows and (Open)SSL.

**Comment by COM8** [comment] 2021-03-19 16:26
Closing this since [cpr v1.6.0](https://github.com/whoshuu/cpr/releases/tag/1.6.0) has been released including a bunch of fixes for Windows and SSL in general.

**Comment by COM8** [comment] 2021-03-19 16:32
Closing this since [cpr v1.6.0](https://github.com/whoshuu/cpr/releases/tag/1.6.0) has been released including a bunch of fixes for Windows and SSL in general.

**Closed by COM8** 2021-03-19 16:32 UTC
Labels: Build :construction_worker:, Windows :tv:
