### ISSUE TITLE
Tests are failing in debug mode due to a destroyed, locked mutex

### ISSUE THREAD

**Issue by smiley** [whoshuu/cpr#46] opened 2015-09-11 11:21 UTC
While looking into exporting test results into XML for actual reporting (more on that later), I saw that tests are passing on my end but marked as failed by CTest.

Looks like this is because the unit tests are destroying some mutex while it's still locked.

```
9:
9: [----------] 8 tests from CallbackPutTests
9: [ RUN      ] CallbackPutTests.CallbackPutLambdaStatusTest
9: [       OK ] CallbackPutTests.CallbackPutLambdaStatusTest (50 ms)
9: [ RUN      ] CallbackPutTests.CallbackPutLambdaTextTest
9: [       OK ] CallbackPutTests.CallbackPutLambdaTextTest (51 ms)
9: [ RUN      ] CallbackPutTests.CallbackPutLambdaStatusReferenceTest
9: [       OK ] CallbackPutTests.CallbackPutLambdaStatusReferenceTest (51 ms)
9: [ RUN      ] CallbackPutTests.CallbackPutLambdaTextReferenceTest
9: [       OK ] CallbackPutTests.CallbackPutLambdaTextReferenceTest (51 ms)
9: [ RUN      ] CallbackPutTests.CallbackPutFunctionStatusTest
9: [       OK ] CallbackPutTests.CallbackPutFunctionStatusTest (51 ms)
9: [ RUN      ] CallbackPutTests.CallbackPutFunctionTextTest
9: [       OK ] CallbackPutTests.CallbackPutFunctionTextTest (51 ms)
9: [ RUN      ] CallbackPutTests.CallbackPutFunctionStatusReferenceTest
9: [       OK ] CallbackPutTests.CallbackPutFunctionStatusReferenceTest (51 ms)
9: [ RUN      ] CallbackPutTests.CallbackPutFunctionTextReferenceTest
9: [       OK ] CallbackPutTests.CallbackPutFunctionTextReferenceTest (51 ms)
9: [----------] 8 tests from CallbackPutTests (407 ms total)
9:
9: [----------] Global test environment tear-down
9: [==========] 40 tests from 5 test cases ran. (2985 ms total)
9: [  PASSED  ] 40 tests.
9: f:\dd\vctools\crt\crtw32\stdcpp\thr\mutex.c(51): mutex destroyed while busy
9/9 Test #9: cpr_callback_tests ...............***Failed    8.93 sec

0% tests passed, 9 tests failed out of 9
```

And it looks like this doesn't happen on AppVeyor because this is a debug check, and tests are run in release mode there. They should be switched to debug mode to catch this sort of thing.

I also found the mutex in question in [server.cpp](https://github.com/whoshuu/cpr/blob/master/test/server.cpp#L367-L371):

``` cpp
void runServer(struct mg_server* server) {
    {
        std::lock_guard<std::mutex> server_lock(server_mutex);
        mg_set_option(server, "listening_port", SERVER_PORT);
        server_cv.notify_one();
    }

    do {
        mg_poll_server(server, 1000);
    } while (!shutdown_mutex.try_lock());

    std::lock_guard<std::mutex> server_lock(server_mutex);
    mg_destroy_server(&server);
    server_cv.notify_one();
}
```

`shutdown_mutex` is locked in the while condition, but isn't unlocked before exiting the scope. GTest also doesn't notice this as this check is done on-destruction -- and `shutdown_mutex` is a global object, so this is thrown in the static deinitiailization phase. (:disappointed:)

`shutdown_mutex` and other assorted utilities should be a class member (and I'm guessing that this wasn't noticed before as this is a test utility class) so any issues would be reported and taken care of at the proper time. (GTest could halt and report a test environment error)

I'm fixing this locally now and pushing in an upcoming PR.

**Comment by smiley** [comment] 2015-09-11 11:22
Hm, hold on. While what I mentioned *does* fix the problem, I see that `unlock` is called in `Server::TearDown`, so it should be working.

**Comment by smiley** [comment] 2015-09-11 11:33
Never mind, that `unlock` takes care of a `lock` in `Server::SetUp`. There's still one missing `unlock`. (Needed in `runServer`)

**Comment by whoshuu** [comment] 2015-09-11 11:36
`runServer` uses a `lock_guard`, so `unlock` is called automatically when it goes out of scope.

**Comment by whoshuu** [comment] 2015-09-11 11:38
Yeah, the server code is a mess, definitely deserves some cleanup!

**Comment by smiley** [comment] 2015-09-11 13:32
Yes, but that `lock_guard` only takes care of `server_mutex`, not `shutdown_mutex` (which gets locked in the `while` condition).

**Comment by whoshuu** [comment] 2015-09-11 13:46
Oh yeah, nice catch! Yeah that definitely is the cause of the exceptions.

**Comment by nabijaczleweli** [comment] 2016-08-16 18:54
Does this still occur?

**Comment by whoshuu** [comment] 2017-10-27 04:52
Better late than never :snail:

**Closed** 2017-10-27 04:51 UTC
Labels: Bug
