### ISSUE TITLE
Use PostAsync/GetAsync got assertion in windows

### ISSUE THREAD

**Issue by jojo0796** [whoshuu/cpr#588] opened 2021-07-13 08:13 UTC
Call AsyncResponse fr = cpr::GetAsync(url); 
       cpr::Response r = fr.get(); =>got assertion

please help to check with attachment
![assertion](https://user-images.githubusercontent.com/87125973/125416427-81f30692-9a2c-463d-ab64-542d691c362f.PNG)
![callback](https://user-images.githubusercontent.com/87125973/125416433-0f477964-7a2b-46cb-aeb5-c4280b949fef.PNG)

**Comment by COM8** [comment] 2021-07-13 13:35
I need a little bit more context than that. Does this also happen for other URLs? Does it work when you run it synchronously?

**Comment by jojo0796** [comment] 2021-07-14 03:00
the code i test only one getasync request and no other thread.

std::string urlstring = "http://www.httpbin.org/get";
cpr::Url url(urlstring);
AsyncResponse fr = cpr::GetAsync(url);
cpr::Response r = fr.get();

Test other URLs get assertion too.

**Comment by jojo0796** [comment] 2021-07-14 03:02
platform is windows 10

**Comment by jojo0796** [comment] 2021-07-14 03:55
Use cpr::Get(url) have no assertion

**Comment by COM8** [comment] 2021-07-16 06:47
For me this works like expected on Linux.
Sadly I do not have access to a system running Windows.
What version of CPR are you using?

**Comment by jojo0796** [comment] 2021-07-16 08:27
CPR version is 1.6.2

on MAC work too. only windows have assertion

**Comment by COM8** [comment] 2021-07-17 11:59
The following test works for me on Windows 10:
![grafik](https://user-images.githubusercontent.com/11741404/126036101-044bd807-3b73-44e0-b88d-93b5d76ade02.png)
```c++
TEST(TestIssue588, AsyncGetTest) {
    std::string urlstring = "http://www.httpbin.org/get";
    cpr::Url url(urlstring);
    AsyncResponse fr = cpr::GetAsync(url);
    cpr::Response r = fr.get();
    EXPECT_EQ(200, r.status_code);
}
```

Could you please share a small example project somewhere, so I can reproduce this one.

**Comment by jojo0796** [comment] 2021-08-03 03:16
CPR&&libcurl build with MDd/MD no assertion
but build with MTd/MT got assertion

Debug Assertion Failed. _ASSERTE(__acrt_first_block == header);

**Comment by WebsocketUser** [comment] 2021-08-03 09:51
build CPR with MDd/MD and exe build with MTd/MT, got assertion when running exe using CPR

**Comment by jojo0796** [comment] 2021-08-03 09:56
build CPR with MDd/MD and exe build with MTd/MT, got assertion when running exe using CPR

**Comment by COM8** [comment] 2021-08-22 08:35
No useful response -> closing

**Closed by COM8** 2021-08-22 08:35 UTC
Labels: Question :question:, Awaiting Resonse :hourglass_flowing_sand:
